# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rawdata',
            table='raw_data',
        ),
    ]
